# Copyright (c) 2020 Ant Group
#
# SPDX-License-Identifier: Apache-2.0
#

dist: bionic
os: linux

language: rust
cache: cargo
rust:
    - 1.49.0

before_install:
    - rustup component add clippy rustfmt
    - sudo modprobe fuse

# override default install
install:
    - make

# override default script
script:
    - rm -rf target-*
    - make docker-smoke
