# Copyright (c) 2020 Ant Group
#
# SPDX-License-Identifier: Apache-2.0
#

dist: bionic
os: linux

language: rust
cache: cargo
rust:
    - stable

before_install:
    - travis_retry rustup component add clippy rustfmt
    - sudo modprobe fuse
    - sudo modprobe kvm
    - ls -l /dev/kvm

# override default install
install:
    - make

# override default script
script:
    - make docker-smoke
